vagrant/catalog/catalog/forms/item.py
from catalog.forms import CSRFForm, ImageFileValidator

from wtforms import Form, TextField, TextAreaField, SelectField, FileField
from wtforms import validators, ValidationError

class ItemForm(CSRFForm):
    """Form for creating and editing items."""

    name = TextField("Name", [validators.Required(), validators.Length(min = 5, max = 120)])

    description = TextAreaField("Description", [validators.Required(), validators.Length(min = 10)])

    category_id = SelectField("Category", coerce = int)

    image = FileField("Image", [ImageFileValidator()])

vagrant/catalog/catalog/views/api.py
"""This module includes most of the routes for the app.

It includes endpoints for viewing and modifying the catalog.
"""

import httplib2
import requests
import json

from flask import abort
from flask import Blueprint
from flask import flash
from flask import Flask
from flask import jsonify
from flask import redirect
from flask import request
from flask import render_template
from flask import session
from flask import url_for

from sqlalchemy.orm.exc import NoResultFound

from database_setup import Base, User, Category, Item
from catalog import app
from catalog import db
from catalog.forms import CSRFForm
from catalog.forms.item import ItemForm

from auth import login_required

api = Blueprint('api', __name__)


################################################################################
# View catalog
################################################################################

# Maximum number of recently created or modified items to show 
LATEST_ITEMS_TO_SHOW = 10

@api.route("/")
@api.route("/catalog/")
def view_catalog():
    """Catalog homepage."""
    categories = db.query(Category).all()
    items = db.query(Item).order_by(Item.name).all()
    latest_items = db.query(Item).order_by(Item.updated.desc()) \
        .limit(LATEST_ITEMS_TO_SHOW).all()
    return render_template("api/catalog.html", 
        categories = categories,
        items = items,
        latest_items = latest_items)


@api.route("/catalog/category/<int:category_id>/")
def view_category(category_id):
    """View a specific category."""
    try:
        category = db.query(Category).filter_by(id = category_id).one()
    except NoResultFound:
        abort(404)
    items = db.query(Item).filter_by(category_id = category.id)
    return render_template("api/category.html", category = category, items = items)


@api.route("/catalog/item/<int:item_id>/")
def view_item(item_id):
    """View a specific item."""
    try:
        item = db.query(Item).filter_by(id = item_id).one()
    except NoResultFound:
        abort(404)
    return render_template("api/item.html", item = item)


################################################################################
# Create/edit/delete items
################################################################################

@api.route("/catalog/item/new/", methods = ['GET', 'POST'])
@login_required
def new_item():
    """Create new item."""
    # populate form
    form = ItemForm(request.form)
    categories = db.query(Category).order_by(Category.name).all() # sort alphabetically
    form.category_id.choices = [(c.id, c.name) for c in categories]

    # display and validate form    
    if request.method != 'POST' or not form.validate():
        return render_template('api/new_item.html', form = form)

    # get image file
    form_file = request.files[form.image.name]
    img_filename = None
    if form_file:
        filename = secure_filename(form_file.filename)
        filename = generate_unique_filename(filename)
        form_file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        img_filename = filename

    # create item
    new_item = Item(
        name = form.name.data,
        description = form.description.data,
        category_id = form.category_id.data,
        image = img_filename,
        user_id = session['user_id'])
    db.add(new_item)
    db.commit()

    flash(message = "Item successfully created", category = "success")

    return redirect(url_for('api.view_item', item_id = new_item.id))

@api.route("/catalog/item/<int:item_id>/edit/", methods = ['GET', 'POST'])
@login_required
def edit_item(item_id):
    """Edit an item."""
    try:
        item = db.query(Item).filter_by(id = item_id).one()
    except NoResultFound:
        abort(404)

    # only author can edit item
    if item.user_id != session['user_id']:
        flash(message = "You are not allowed to update this item", category = "error")
        return render_template("api/item.html", item = item)

    # populate form
    form = ItemForm(request.form, item)
    categories = db.query(Category).order_by(Category.name).all() # sort alphabetically
    form.category_id.choices = [(c.id, c.name) for c in categories]

    # display and validate form
    if request.method != 'POST' or not form.validate():
        return render_template('api/edit_item.html', form = form, item = item)

    # get image file
    form_file = request.files[form.image.name]
    img_filename = None
    if form_file:
        filename = secure_filename(form_file.filename)
        filename = generate_unique_filename(filename)
        form_file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        img_filename = filename

    # edit item
    item.name = form.name.data
    item.description = form.description.data
    item.category_id = form.category_id.data
    # only replace image if new image is uploaded
    if img_filename:
        item.image = img_filename
    db.add(item)
    db.commit()

    flash(message = "Item successfully updated", category = "success")

    return redirect(url_for('api.view_item', item_id = item.id))

@api.route("/catalog/item/<int:item_id>/delete/", methods = ['GET', 'POST'])
@login_required
def delete_item(item_id):
    """Delete an item."""
    try:
        item = db.query(Item).filter_by(id = item_id).one()
    except NoResultFound:
        abort(404)

    # only author can delete item
    if item.user_id != session['user_id']:
        flash(message = "You are not allowed to remove this item", category = "error")
        return render_template("api/item.html", item = item)

    # populate form - just a base form here for csrf validation
    form = CSRFForm(request.form)

    # display and validate form
    if request.method != 'POST' or not form.validate():
        return render_template('api/delete_item.html', form = form, item = item)

    # delete the item
    db.delete(item)
    db.commit()

    flash(message = "Item successfully removed", category = "success")

    return redirect(url_for('api.view_catalog'))


################################################################################
# User info
################################################################################

@api.route("/user/profile/")
@login_required
def user_profile():
    """View current user's profile page."""
    user_id = session["user_id"]
    user = db.query(User).filter_by(id = user_id).one()
    # sort user items alphabetically 
    items = db.query(Item).filter_by(user_id = user_id).order_by(Item.name).all()
    return render_template("api/user.html", user = user, items = items)


################################################################################
# Image upload
################################################################################

import os
import datetime
import string
import random
import uuid
from werkzeug import secure_filename
from flask import send_from_directory

def generate_random_string():
    """Generate a random string with alphabetic characters and digits."""
    alpha = string.ascii_lowercase + string.ascii_uppercase + string.digits
    rand_str = "".join(random.choice(alpha) for x in xrange(32))
    return rand_str

def generate_unique_filename(original_filename):
    """Generate a unique name for a file.

    The current implementation does not actually guarantee uniqueness,
    but the probability of generating the same name twice is very low.

    The generated file names include the date and time, and a random UUID.

    Args:
      original_filename: the original name of the file.
    Returns:
      A file name with the same extension as the original file, and
      which is almost surely unique.
    """
    # keep file extension, in lower case
    ext = os.path.splitext(original_filename)[1].strip().lower()

    # current date and time
    date_time = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")

    # generate random uuid
    uuid_hex = uuid.uuid4().hex

    filename = "_".join([date_time, uuid_hex, ext])
    return filename


@api.route("/image/<string:filename>/")
def view_image(filename):
    """View uploaded image."""
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename)

def get_image_url(filename):
    """Get URL for an image file.

    If no file is specified, returns a URL for a place holder image.

    Note that this method does not check if the file actually exists.
    """
    if filename:
        return url_for("api.view_image", filename = filename)
    else:
        return "https://placehold.it/300x300.png?text=No+image"

################################################################################

# Expose utility functions to templates
# http://flask.pocoo.org/docs/0.10/templating/
@api.context_processor
def utility_processor():
    return dict(get_image_url = get_image_url)

################################################################################

vagrant/catalog/catalog/views/data.py
"""This module includes routes for getting data in special formats from the app.

It includes endpoints for getting catalog data in JSON format, and Atom feeds.
"""

from flask import abort
from flask import Blueprint

from sqlalchemy.orm.exc import NoResultFound

from catalog import db
from database_setup import User, Category, Item

from auth import login_required

data = Blueprint('data', __name__)


################################################################################
# JSON
################################################################################

from flask import jsonify

@data.route('/catalog.json')
def view_catalog_json():
    """Catalog in json format."""
    categories = db.query(Category).all()
    items = db.query(Item).all()
    return jsonify(categories = [c.serialize for c in categories],
        items = [i.serialize for i in items])

@data.route("/catalog/category-<int:category_id>.json")
def view_category_json(category_id):
    """Category in json format."""
    try:
        category = db.query(Category).filter_by(id = category_id).one()
    except NoResultFound:
        abort(404)
    items = db.query(Item).filter_by(category_id = category.id).all()
    return jsonify(category = category.serialize,
        items = [i.serialize for i in items])

@data.route("/catalog/item-<int:item_id>.json")
def view_item_json(item_id):
    """Item in json format."""
    try:
        item = db.query(Item).filter_by(id = item_id).one()
    except NoResultFound:
        abort(404)
    return jsonify(item = item.serialize)

@data.route('/users.json')
@login_required
def users_json():
    """List of users in json format.

    This is for debugging and should probably be removed or protected.

    TODO (pt314): Remove or protect this endpoint.
    """
    users = db.query(User).all()
    return jsonify(users = [u.serialize for u in users])


################################################################################
# Atom
################################################################################
#
# See:
#
# Generating Feeds with Flask
# http://flask.pocoo.org/snippets/10/
#
# Atom Syndication
# http://werkzeug.pocoo.org/docs/0.11/contrib/atom/
#
################################################################################

from urlparse import urljoin
from flask import request
from flask import url_for
from werkzeug.contrib.atom import AtomFeed

# Number of items to include in atom feed
ATOM_FEED_SIZE = 5

def make_external(url):
    """Convert relative URL to absolute URL."""
    return urljoin(request.url_root, url)

@data.route('/recent.atom')
def recent_atom_feed():
    """Atom feed with recently created and updated items."""
    feed = AtomFeed('Latest Items', 
        feed_url = request.url, url = request.url_root)
    items = db.query(Item).order_by(Item.updated.desc()).limit(ATOM_FEED_SIZE).all()
    for item in items:
        item_url = url_for('api.view_item', item_id = item.id)
        feed.add(title = item.name,
                 content = unicode(item.name + " (" + item.category.name + "): " + item.description),
                 content_type = 'text',
                 author = item.user.name,
                 url = make_external(item_url),
                 updated = item.updated,
                 published = item.created)
    return feed.get_response()

################################################################################

vagrant/catalog/catalog/templates/api/catalog.html
{% extends "_main.html" %}

{% block page_header %}

<h1>Item catalog</h1>
<p>Welcome to the item catalog web app!</p>
<p>The perfect place to keep track of your items :)</p>
<!--
<p>
    <a class="col" href="{{ url_for('data.view_catalog_json') }}"><span class="glyphicon glyphicon-file"></span> Catalog JSON</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('data.recent_atom_feed') }}"><span class="glyphicon glyphicon-list"></span> Atom feed</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('api.new_item') }}"><span class="glyphicon glyphicon-plus"></span> Add item</a>
</p>
-->

{% endblock %}


{% block content %}

<div class="row">

<div class="col-sm-4">
<p>
    <a class="col" href="{{ url_for('data.view_catalog_json') }}"><span class="glyphicon glyphicon-download-alt"></span> Catalog JSON</a>
</p>
    <h2>Categories</h2>
    <ul>
    {% for c in categories %}
    	<li>
            <a href="{{ url_for('api.view_category', category_id = c.id) }}">{{ c.name }}</a>
            <small>({{ c.items | count }} items)</small>
        </li>
    {% endfor %}
    </ul>
</div>

<div class="col-sm-4">
<p>
    <a class="col" href="{{ url_for('data.recent_atom_feed') }}"><span class="glyphicon glyphicon-list"></span> Atom feed</a>
</p>
    <h2>Latest items</h2>
    <ul>
    {% for i in latest_items %}
        <li>
            <a href="{{ url_for('api.view_item', item_id = i.id) }}">{{ i.name }}</a>
            <small>(<a href="{{ url_for('api.view_category', category_id = i.category.id) }}">{{ i.category.name }}</a>)</small>
        </li>
    {% endfor %}
    </ul>
</div>

<div class="col-sm-4">
<p>
    <a class="col" href="{{ url_for('api.new_item') }}"><span class="glyphicon glyphicon-plus"></span> Add item</a>
</p>
    <h2>All items</h2>
    <ul>
    {% for i in items %}
    	<li>
            <a href="{{ url_for('api.view_item', item_id = i.id) }}">{{ i.name }}</a>
            <small>(<a href="{{ url_for('api.view_category', category_id = i.category.id) }}">{{ i.category.name }}</a>)</small>
        </li>
    {% endfor %}
    </ul>
</div>

</div>

{% endblock %}

vagrant/catalog/catalog/templates/api/category.html
{% extends "_main.html" %}

{% block page_header %}

<h1>Category: {{ category.name }}</h1>

<p>
    <a class="col" href="{{ url_for('api.view_catalog') }}"><span class="glyphicon glyphicon-home"></span> Catalog home</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('data.view_category_json', category_id = category.id) }}"><span class="glyphicon glyphicon-download-alt"></span> Category JSON</a>
</p>

{% endblock %}


{% block content %}

<h2>Items ({{ category.items | count }} items)</h2>
<ul>
{% for i in items %}
	<li>
        <a href="{{ url_for('api.view_item', item_id = i.id) }}">{{ i.name }}</a>
    </li>
{% endfor %}
</ul>

{% endblock %}

vagrant/catalog/catalog/templates/api/delete_item.html
{% extends "_main.html" %}

{% block page_header %}

<h1>Delete item: {{ item.name }}</h1>

<p>
    <a class="col" href="{{ url_for('api.view_catalog') }}"><span class="glyphicon glyphicon-home"></span> Catalog home</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('api.view_category', category_id = item.category_id) }}"><span class="glyphicon glyphicon-folder-close"></span> Category home</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('data.view_item_json', item_id = item.id) }}"><span class="glyphicon glyphicon-download-alt"></span> Item JSON</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('api.view_item', item_id = item.id) }}"><span class="glyphicon glyphicon-file"></span> View item</a>
    {% if item.user_id == session["user_id"] %}
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('api.edit_item', item_id = item.id) }}"><span class="glyphicon glyphicon-pencil"></span> Edit item</a>
    {% endif %}
</p>

{% endblock %}


{% block content %}

{% from "_form_helpers.html" import render_csrf_field %}
<form method="POST" enctype="multipart/form-data" action="{{ url_for('api.delete_item', item_id = item.id) }}">
    {{ render_csrf_field(form) }}
    <div class="row">
        <div class="col-sm-6">
            <dl class="dl-horizontal">
                <dt>Name:</dt>
                    <dd>{{ item.name }}</dd>
                <dt>Description:</dt>
                    <dd>
                    {% if item.description %}
                        {{ item.description }}
                    {% else %}
                        &nbsp;
                    {% endif %}
                    </dd>
                <dt>Category:</dt>
                    <dd><a href="{{ url_for('api.view_category', category_id = item.category_id) }}">{{ item.category.name }}</a></dd>
                <dt>Created by:</dt>
                    <dd>{{ item.user.name }}</dd>
                <dt>Created on:</dt>
                    <dd>{{ item.created.strftime("%Y-%m-%d %H:%M:%S") }}</dd>
                <dt>Last modified:</dt>
                    <dd>{{ item.updated.strftime("%Y-%m-%d %H:%M:%S") }}</dd>
            </dl>
        </div>
        <div class="col-sm-6 text-right">
            <img width="300" src="{{ get_image_url(item.image) }}">
        </div>
    </div>
    <input type="submit" class="btn btn-danger btn-block" value="Delete"/>
    <a class="btn btn-default btn-block" href="{{ url_for('api.view_item', item_id = item.id) }}">Cancel</a><br/>
</form>

{% endblock %}

vagrant/catalog/catalog/templates/api/edit_item.html
{% extends "_main.html" %}

{% block page_header %}

<h1>Edit item: {{ item.name }}</h1>

<p>
    <a class="col" href="{{ url_for('api.view_catalog') }}"><span class="glyphicon glyphicon-home"></span> Catalog home</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('api.view_category', category_id = item.category_id) }}"><span class="glyphicon glyphicon-folder-close"></span> Category home</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('data.view_item_json', item_id = item.id) }}"><span class="glyphicon glyphicon-download-alt"></span> Item JSON</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('api.view_item', item_id = item.id) }}"><span class="glyphicon glyphicon-file"></span> View item</a>
    {% if item.user_id == session["user_id"] %}
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('api.delete_item', item_id = item.id) }}"><span class="glyphicon glyphicon-trash"></span> Delete item</a>
    {% endif %}
</p>

{% endblock %}


{% block content %}

{% from "_form_helpers.html" import render_csrf_field %}
{% from "_form_helpers.html" import render_field %}
<form method="POST" enctype="multipart/form-data" action="{{ url_for('api.edit_item', item_id = item.id) }}">
    {{ render_csrf_field(form) }}
    <div class="row">
        <div class="col-sm-6">
            {{ render_field(form.name) }}
            {{ render_field(form.description, rows = 5) }}
            {{ render_field(form.category_id) }}
            {{ render_field(form.image) }}
        </div>
        <div class="col-sm-6 text-right">
            <img id="image" name="image" width="300" src="{{ get_image_url(item.image) }}">
        </div>
    </div>
    <dl class="dl-horizontal">
        <dt>Created by:</dt>
            <dd>{{ item.user.name }}</dd>
        <dt>Created on:</dt>
            <dd>{{ item.created.strftime("%Y-%m-%d %H:%M:%S") }}</dd>
        <dt>Last modified:</dt>
            <dd>{{ item.updated.strftime("%Y-%m-%d %H:%M:%S") }}</dd>
    </dl>
    <input type="submit" class="btn btn-primary btn-block" value="Save"/>
    <a class="btn btn-default btn-block" href="{{ url_for('api.view_item', item_id = item.id) }}">Cancel</a><br/>
</form>

{% endblock %}

vagrant/catalog/catalog/templates/api/item.html
{% extends "_main.html" %}

{% block page_header %}

<h1>Item: {{ item.name }}</h1>

<p>
    <a class="col" href="{{ url_for('api.view_catalog') }}"><span class="glyphicon glyphicon-home"></span> Catalog home</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('api.view_category', category_id = item.category_id) }}"><span class="glyphicon glyphicon-folder-close"></span> Category home</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('data.view_item_json', item_id = item.id) }}"><span class="glyphicon glyphicon-download-alt"></span> Item JSON</a>
    {% if item.user_id == session["user_id"] %}
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('api.edit_item', item_id = item.id) }}"><span class="glyphicon glyphicon-pencil"></span> Edit item</a>
    &nbsp;|&nbsp;
    <a class="col" href="{{ url_for('api.delete_item', item_id = item.id) }}"><span class="glyphicon glyphicon-trash"></span> Delete item</a>
    {% endif %}
</p>

{% endblock %}


{% block content %}

<div class="row">
    <div class="col-sm-6">
        <dl class="dl-horizontal">
            <dt>Name:</dt>
                <dd>{{ item.name }}</dd>
            <dt>Description:</dt>
                <dd>
                {% if item.description %}
                    {{ item.description }}
                {% else %}
                    &nbsp;
                {% endif %}
                </dd>
            <dt>Category:</dt>
                <dd><a href="{{ url_for('api.view_category', category_id = item.category_id) }}">{{ item.category.name }}</a></dd>
            <dt>Created by:</dt>
                <dd>{{ item.user.name }}</dd>
            <dt>Created on:</dt>
                <dd>{{ item.created.strftime("%Y-%m-%d %H:%M:%S") }}</dd>
            <dt>Last modified:</dt>
                <dd>{{ item.updated.strftime("%Y-%m-%d %H:%M:%S") }}</dd>
        </dl>
    </div>
    <div class="col-sm-6 text-right">
        <img width="300" src="{{ get_image_url(item.image) }}">
    </div>
</div>

{% endblock %}

vagrant/catalog/catalog/templates/api/new_item.html
{% extends "_main.html" %}

{% block page_header %}

<h1>New item</h1>

<p>
    <a class="col" href="{{ url_for('api.view_catalog') }}"><span class="glyphicon glyphicon-home"></span> Catalog home</a>
</p>

{% endblock %}


{% block content %}

{% from "_form_helpers.html" import render_csrf_field %}
{% from "_form_helpers.html" import render_field %}
<form method="POST" enctype="multipart/form-data" action="{{ url_for('api.new_item') }}">
    {{ render_csrf_field(form) }}
    {{ render_field(form.name) }}
    {{ render_field(form.description, rows = 5) }}
    {{ render_field(form.category_id) }}
    {{ render_field(form.image) }}
    <input type="submit" class="btn btn-primary btn-block" value="Save"/>
    <a class="btn btn-default btn-block" href="{{ url_for('api.view_catalog') }}">Cancel</a><br/>
</form>

{% endblock %}

vagrant/catalog/catalog/templates/api/user.html
{% extends "_main.html" %}

{% block page_header %}

<h1>User profile</h1>

{% endblock %}


{% block content %}

<div class="row">
    <div class="col-sm-6">
        <dl class="dl-horizontal">
            <dt>Name:</dt>
                <dd>{{ user.name }}</dd>
            <dt>Email:</dt>
                <dd>{{ user.email }}</dd>
        </dl>
        <div class="text-center">
            <img class="img-circle" width="200" src="{{ user.picture }}">
        </div>
    </div>
    <div class="col-sm-6">
        <h2>Items</h2>
        <ul>
        {% for i in items %}
            <li>
                <a href="{{ url_for('api.view_item', item_id = i.id) }}">{{ i.name }}</a>
                <small>(<a href="{{ url_for('api.view_category', category_id = i.category.id) }}">{{ i.category.name }}</a>)</small>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>


{% endblock %}